apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-sxapi
  labels:
    app: demo-sxapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-sxapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-sxapi
    spec:
      containers:
        - name: webserver
          image: "nginx:1.7.9"
          env:
            - name: SERVICE_INJECTED
              value: $(MY_SERVICE_NAME)
            - name: SX_DEBUG
              value: "true"
          envFrom:
            - configMapRef:
                name: demo-sxapi-config
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
