apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
nameSuffix: -single

# Incremental changes
patchesStrategicMerge:
- patches/scale-down.yaml

# Stay to nginx 1.9.0
images:
- name: nginx
  newTag: 1.9.0
