apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: dev-

# Example of incremental change for the image
images:
- name: nginx
  newName: nginx
  newTag: 1.9.2
- name: quay.io/app-sre/nginx
  newName: nginx
  newTag: 1.9.2

# Example of incremental change for the deployment
patchesStrategicMerge:
- patches/scale-down.yaml
  