apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-sxapi
spec:
  template:
    spec:      
      containers:
        - name: linux
          envFrom:
            - configMapRef:
                name: demo-sxapi-config-testing