apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
nameSuffix: -0.2.99

resources:
- cm-config.yaml

patchesStrategicMerge:
- patches/deployment-config-0.2.99.yaml
- patches/delete-config.yaml

images:
- name: startx/sxapi
  newName: startx/sxapi
  newTag: "0.2.99"