apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
nameSuffix: -default

# Common to all configmaps and secrets.
generatorOptions:
  labels:
    common_label: default
  annotations:
    common_annotation: default

# Example of incremental change for the image
images:
- name: nginx
  newName: quay.io/app-sre/nginx
  newTag: 1.9.0
- name: quay.io/app-sre/nginx
  newName: nginx
  newTag: 1.9.1

# Example of incremental change for the deployment
patchesStrategicMerge:
- patches/add-env.yaml
- patches/scale-up.yaml


# Example of incremental change with a patch
patchesJson6902:
- target:
    version: v1
    kind: Service
    name: example
  path: patches/add-label.yaml