apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  annotations:
    openshift.io/generated-by: sx-kustomize-cli
  labels:
    app: "demo-pod"
    version: "0.0.11"
    app.startx.fr/scope: "base"
    app.startx.fr/cluster: "mycluster"
    app.startx.fr/env: "dev"
    app.startx.fr/component: "demo-pod"
    app.kubernetes.io/component: "demo-pod"
    app.kubernetes.io/name: "demo-pod-pod"
    app.kubernetes.io/version: "0.0.11"
    app.kubernetes.io/part-of: demo
spec:
  containers:
    - name: linux
      image: "quay.io/startx/fedora:latest"
      env:
        - name: SX_DEBUG
          value: "true"
        - name: SX_VERBOSE
          value: "true"
      command:
        - "/bin/sx"
      args:
        - "run"
      livenessProbe:
        exec:
          command:
            - "/bin/sx"
            - isLive
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        exec:
          command:
            - "/bin/sx"
            - isReady
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      resources:
        limits:
          cpu: 200m
          memory: 64Mi
        requests:
          cpu: 20m
          memory: 32Mi
      terminationMessagePath: "/dev/termination-log"
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}