kind: LimitRange
apiVersion: v1
metadata:
  name: "demo-sxapi-limits"
  namespace: "demo-sxapi"
  annotations:
    openshift.io/generated-by: sx-kustomize-cli
  labels:
    app: "demo-sxapi"
    version: "0.0.11"
    app.startx.fr/scope: "base"
    app.startx.fr/cluster: "mycluster"
    app.startx.fr/env: "dev"
    app.startx.fr/component: "demo-sxapi"
    app.kubernetes.io/component: "demo-sxapi"
    app.kubernetes.io/name: "demo-sxapi-limitrange"
    app.kubernetes.io/version: "0.0.11"
    app.kubernetes.io/part-of: demo
spec:
  limits:
    - type: "Pod"
      min:
        cpu: "20m"
        memory: "32Mi"
      max:
        cpu: 500m
        memory: 600Mi
    - type: "Container"
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 20m
        memory: 32Mi
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: 400m
        memory: 512Mi
