kind: ResourceQuota
apiVersion: v1
metadata:
  name: "demo-sxapi-quotas"
  namespace: "demo-sxapi"
  annotations:
    openshift.io/generated-by: sx-kustomize-cli
  labels:
    app: "demo-sxapi"
    version: "0.0.1"
    app.startx.fr/scope: "base"
    app.startx.fr/cluster: "mycluster"
    app.startx.fr/env: "dev"
    app.startx.fr/component: "demo-sxapi"
    app.kubernetes.io/component: "demo-sxapi"
    app.kubernetes.io/name: "demo-sxapi-project"
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/part-of: demo
spec:
  hard:
    limits.cpu: "2000m"
    limits.memory: "2500Mi"
    requests.cpu: "500m"
    requests.memory: "1200Mi"
    requests.storage: "0"
    persistentvolumeclaims: "0"
    ephemeral-storage: "0" 
    gp2.storageclass.storage.k8s.io/requests.storage: "0"
    gp2.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    aws-generic-retain.storageclass.storage.k8s.io/requests.storage: "0"
    aws-generic-retain.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    aws-generic-delete.storageclass.storage.k8s.io/requests.storage: "0"
    aws-generic-delete.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    aws-fast-retain.storageclass.storage.k8s.io/requests.storage: "0"
    aws-fast-retain.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    aws-fast-delete.storageclass.storage.k8s.io/requests.storage: "0"
    aws-fast-delete.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    aws-slow-retain.storageclass.storage.k8s.io/requests.storage: "0"
    aws-slow-retain.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    aws-slow-delete.storageclass.storage.k8s.io/requests.storage: "0"
    aws-slow-delete.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    ocs-generic-delete.storageclass.storage.k8s.io/requests.storage: "0"
    ocs-generic-delete.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    ocs-generic-retain.storageclass.storage.k8s.io/requests.storage: "0"
    ocs-generic-retain.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    ocs-fs-delete.storageclass.storage.k8s.io/requests.storage: "0"
    ocs-fs-delete.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    ocs-fs-retain.storageclass.storage.k8s.io/requests.storage: "0"
    ocs-fs-retain.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    ocs-storagecluster-ceph-rbd.storageclass.storage.k8s.io/requests.storage: "0"
    ocs-storagecluster-ceph-rbd.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    openshift-storage.noobaa.io.storageclass.storage.k8s.io/requests.storage: "0"
    openshift-storage.noobaa.io.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    pods: "15"
    services.loadbalancers: "0"
    services.nodeports: "0"
    secrets: "40"
    configmaps: "40"
    replicationcontrollers: "10"
    openshift.io/imagestreams: "7"
    count/daemonsets.apps: "0"
    count/replicasets.apps: "20"
    count/deployments.apps: "10"
    services: "10"
