apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../default
nameSuffix: -testing

resources:
- cm-config.yaml

patchesStrategicMerge:
- patches/deployment-config-testing.yaml
- patches/delete-config.yaml

images:
- name: startx/sxapi
  newName: startx/sxapi
  newTag: "testing"