apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
nameSuffix: -testing

resources:
- cm-config.yaml

patchesStrategicMerge:
- patches/route.yaml

images:
- name: startx/sxapi
  newName: startx/sxapi
  newTag: "testing"